baseURL = "mrsalta.github.io"
languageCode = "en-us"
title = "Andrew is Testing"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 5

[sitemap]
	changefreq = "monthly"
	priority = 0.5
	filename = "sitemap.xml"
	
[params]
	favicon = ""
	description = "Just playing around. Nothing to see here."
	facebook = ""
	twitter = ""
	instagram = ""
	youtube = ""
	github = ""
	gitlab = ""
	linkedin = ""
	# choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
	background_color_class = "bg-dark-gray"
	featured_image = ""
	recent_posts_number = 2